# Generated by Django 2.2.2 on 2020-06-23 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('establishment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_hours', models.DateTimeField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('job', models.ManyToManyField(to='establishment.Job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.User')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='establishment.Vacancy')),
            ],
            options={
                'db_table': 'tb_scheduling',
            },
        ),
    ]
