# Generated by Django 2.2.2 on 2020-04-23 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establishment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('establishment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='establishment.Establishment')),
            ],
            options={
                'db_table': 'tb_day_book',
            },
        ),
    ]
