# Generated by Django 3.0.5 on 2020-04-28 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Every day'), (2, 'Working days'), (3, 'Weekends')], default=2)),
                ('hour_opened', models.TimeField()),
                ('hour_closed', models.TimeField()),
            ],
            options={
                'db_table': 'tb_availability',
            },
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tb_establishment',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=300, unique=True)),
                ('establishment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='establishment.Establishment')),
            ],
            options={
                'db_table': 'tb_photo',
            },
        ),
    ]
