# Generated by Django 3.0.5 on 2020-05-06 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0002_auto_20200428_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='establishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='availabilities', to='establishment.Establishment'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='type',
            field=models.IntegerField(choices=[(0, 'Every day'), (1, 'Working days'), (2, 'Weekends')]),
        ),
        migrations.AlterField(
            model_name='photo',
            name='establishment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='photos', to='establishment.Establishment'),
        ),
    ]
