# Generated by Django 3.0.5 on 2020-04-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tb_event',
            },
        ),
    ]
