# Generated by Django 3.0.5 on 2020-04-28 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('establishment', '0002_auto_20200428_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'Available'), (2, 'Done'), (3, 'Reserved'), (4, 'Waiting')],
                                               default=1)),
                ('client',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('establishment',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='establishment.Establishment')),
            ],
            options={
                'db_table': 'tb_event',
            },
        ),
    ]
