# Generated by Django 3.0.5 on 2020-05-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(1, 'Available'), (2, 'Done'), (3, 'Reserved'), (4, 'Waiting')],
                                               default=3)),
            ],
            options={
                'db_table': 'tb_event',
            },
        ),
    ]
