# Generated by Django 3.0.5 on 2020-05-07 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('establishment', '0002_auto_20200507_1105'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='establishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events',
                                    to='establishment.Establishment'),
        ),
    ]
