# Generated by Django 3.0.5 on 2020-05-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.IntegerField(choices=[(1, 'Available'), (2, 'Done'), (3, 'Reserved'), (4, 'Waiting')],
                                      default=3),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
